version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "producer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vuzwa12dy7gw"
s3_prefix = "producer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
